/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
/** ID lister. */
package Components;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Num = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int TIMES = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int EL = 11;
  /** RegularExpression Id. */
  int LET = 12;
  /** RegularExpression Id. */
  int IN = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int ISEQ = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int GT = 20;
  /** RegularExpression Id. */
  int LT = 21;
  /** RegularExpression Id. */
  int GE = 22;
  /** RegularExpression Id. */
  int LE = 23;
  /** RegularExpression Id. */
  int EQ = 24;
  /** RegularExpression Id. */
  int NEW = 25;
  /** RegularExpression Id. */
  int SEQ = 26;
  /** RegularExpression Id. */
  int ASSIGN = 27;
  /** RegularExpression Id. */
  int DESREF = 28;
  /** RegularExpression Id. */
  int IF = 29;
  /** RegularExpression Id. */
  int THEN = 30;
  /** RegularExpression Id. */
  int ELSE = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int DO = 33;
  /** RegularExpression Id. */
  int BOOL = 34;
  /** RegularExpression Id. */
  int FUN = 35;
  /** RegularExpression Id. */
  int IS = 36;
  /** RegularExpression Id. */
  int COLON = 37;
  /** RegularExpression Id. */
  int INT_T = 38;
  /** RegularExpression Id. */
  int BOOL_T = 39;
  /** RegularExpression Id. */
  int REF_T = 40;
  /** RegularExpression Id. */
  int STR_T = 41;
  /** RegularExpression Id. */
  int PRINTLN = 42;
  /** RegularExpression Id. */
  int LCB = 43;
  /** RegularExpression Id. */
  int RCB = 44;
  /** RegularExpression Id. */
  int QUOTE = 45;
  /** RegularExpression Id. */
  int DOT = 46;
  /** RegularExpression Id. */
  int Id = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\",\"",
    "\"~\"",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"=\"",
    "\"new\"",
    "\";\"",
    "\":=\"",
    "\"!\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "<BOOL>",
    "\"fun\"",
    "\"->\"",
    "\":\"",
    "\"int\"",
    "\"bool\"",
    "\"ref\"",
    "\"string\"",
    "\"println\"",
    "\"{\"",
    "\"}\"",
    "\"\\\"\"",
    "\".\"",
    "<Id>",
  };

}
